name: Masak APK Laundry

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Java 17 (Wajib buat Android SDK terbaru)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # INI RESEP RAHASIANYA:
      # Kita install 'nasm' (buat FFmpeg) dan 'libtool-bin'.
      # Kita JANGAN install 'ffmpeg' sistem biar gak konflik.
      - name: Install Alat Tukang (Tanpa Konflik)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git python3 python3-dev \
            libffi-dev libssl-dev automake autoconf \
            libtool libtool-bin pkg-config zip unzip zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 cmake \
            nasm yasm gettext

      - name: Install Buildozer & Cython
        run: |
          pip3 install --upgrade pip
          # Kita kunci Cython di versi stabil Kivy
          pip3 install "Cython==0.29.33"
          pip3 install buildozer

      - name: Mulai Masak APK
        # yes | untuk auto-accept semua pertanyaan
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Hasil Masakan
        uses: actions/upload-artifact@v4
        with:
          name: Laundry-APK
          path: bin/*.apk
